[general]
import = [
    "~/.config/alacritty/themes/themes/linux.toml"
]

[window]
# padding = { x = 4, y = 4 }
opacity = 1

[font]
size = 12

[font.normal]
family = "Iosevka Term"
style = "Medium"

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[cursor]
style = { shape = "Beam", blinking = "On" }

[scrolling]
history = 10000

